# Load Model (Training)

In [1]:
import torch
from cldm.toss import TOSS
from cldm.model import load_state_dict
from omegaconf import OmegaConf

from ldm.util import instantiate_from_config

config = OmegaConf.load("models/toss_vae.yaml")
model = instantiate_from_config(config.model)
lora_config_params = model.model.diffusion_model.peft_config['default']

# 1. Get raw state dict
raw_sd = torch.load("ckpt/toss.ckpt", map_location="cpu", weights_only=False)["state_dict"] # Load parameters from checkpoint
new_sd = {}

true_count = 0
false_count = 0
# 2. Targeted Remapping
for k, v in raw_sd.items():
    # Fix the PEFT wrapper prefix first
    nk = k.replace("model.diffusion_model.", "model.diffusion_model.base_model.model.")
    
    # CRITICAL: If this is a LoRA target module, it MUST end in .base_layer.weight
    # Check if the original key (k) contains any of your target module names
    is_target = any(target in k for target in lora_config_params.target_modules)
    
    if is_target:
        true_count += 1
        # e.g., to_q.weight -> to_q.base_layer.weight
        nk = nk.replace(".weight", ".base_layer.weight")
        nk = nk.replace(".bias", ".base_layer.bias")
    else:
        false_count += 1
    new_sd[nk] = v

# 3. Load into model
missing, unexpected = model.load_state_dict(new_sd, strict=False) # Iteratre through state_dict and match the params
print("Missing:", missing) # Keys that the model has but the state_dict does not 
print("Unexpected:", unexpected) # Keys that the model does not have but the state_dict does
print("True Count:", true_count)
print("False Count:", false_count)

# 4. Verify: Only lora_A/lora_B should be missing now
final_missing = [m for m in missing if "lora_" not in m]
print(f"CRITICAL MISSING (Should be empty): {final_missing}")

c:\Users\user\miniconda3\envs\toss_temp\lib\site-packages\lightning_fabric\__init__.py:29: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  __import__("pkg_resources").declare_namespace(__name__)
c:\Users\user\miniconda3\envs\toss_temp\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


No module 'xformers'. Proceeding without it.
[PATCH] Disabled gradient checkpointing in ldm_util.checkpoint
TossLoraModule: Running in eps-prediction mode


c:\Users\user\miniconda3\envs\toss_temp\lib\site-packages\pytorch_lightning\utilities\distributed.py:258: LightningDeprecationWarning: `pytorch_lightning.utilities.distributed.rank_zero_only` has been deprecated in v1.8.1 and will be removed in v2.0.0. You can import it from `pytorch_lightning.utilities` instead.
  rank_zero_deprecation(


DiffusionWrapper has 863.65 M params.
making attention of type 'vanilla' with 512 in_channels
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla' with 512 in_channels


wandb: [wandb.login()] Loaded credentials for https://api.wandb.ai from C:\Users\user\_netrc.
wandb: Currently logged in as: wndyd0131 (wndyd0131-sungkyunkwan-university) to https://api.wandb.ai. Use `wandb login --relogin` to force relogin


[INIT] Modules with checkpointing enabled: 0
[INIT] Unfreezing pose_net param: base_model.model.pose_net.0.weight, shape=torch.Size([320, 51])
[INIT] Unfreezing pose_net param: base_model.model.pose_net.0.bias, shape=torch.Size([320])
[INIT] Unfreezing pose_net param: base_model.model.pose_net.2.weight, shape=torch.Size([320, 320])
[INIT] Unfreezing pose_net param: base_model.model.pose_net.2.bias, shape=torch.Size([320])
[INIT] Unfroze 4 pose_net parameters
[INIT] lora_B before init: base_model.model.middle_block.1.transformer_blocks.0.attn1.to_q.lora_B.default.weight, mean=0.000000e+00
[INIT] lora_B after init: base_model.model.middle_block.1.transformer_blocks.0.attn1.to_q.lora_B.default.weight, mean=1.249272e-03
[INIT] lora_B before init: base_model.model.middle_block.1.transformer_blocks.0.attn1.to_k.lora_B.default.weight, mean=0.000000e+00
[INIT] lora_B after init: base_model.model.middle_block.1.transformer_blocks.0.attn1.to_k.lora_B.default.weight, mean=1.257335e-03
[INIT] lora

c:\Users\user\miniconda3\envs\toss_temp\lib\site-packages\torchvision\models\_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
c:\Users\user\miniconda3\envs\toss_temp\lib\site-packages\torchvision\models\_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=VGG16_Weights.IMAGENET1K_V1`. You can also use `weights=VGG16_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)


Loading model from: c:\Users\user\miniconda3\envs\toss_temp\lib\site-packages\lpips\weights\v0.1\vgg.pth
[INIT] Initialized LPIPS perceptual loss (VGG backbone)

[DEBUG] LoRA Layer Analysis:
  base_model.model.middle_block.1.transformer_blocks.0.attn1.to_q:
    scaling: {'default': 1.0}
    disable_adapters: False
    merged: False
    lora_A[default]: shape=torch.Size([16, 1280]), requires_grad=True
    lora_B[default]: shape=torch.Size([1280, 16]), requires_grad=True

[DEBUG] Active adapter: default
[DEBUG] Active adapters: ['default']

[DEBUG] Pose Net Weight Analysis:
  pose_net structure: Sequential(
  (0): Linear(in_features=51, out_features=320, bias=True)
  (1): SiLU()
  (2): Linear(in_features=320, out_features=320, bias=True)
)
  pose_enc type: vae

  Layer: pose_net.0.weight
    shape: torch.Size([320, 51])
    requires_grad: True
    mean: 0.000658
    std: 0.081311
    min: -0.140024
    max: 0.140022
    abs_mean: 0.070315

  Layer: pose_net.0.bias
    shape: torch.Size([

c:\Users\user\miniconda3\envs\toss_temp\lib\site-packages\lpips\lpips.py:107: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  self.load_state_dict(torch.load(model_path, map_l

Missing: ['model.diffusion_model.base_model.model.middle_block.1.transformer_blocks.0.attn1.to_q.lora_A.default.weight', 'model.diffusion_model.base_model.model.middle_block.1.transformer_blocks.0.attn1.to_q.lora_B.default.weight', 'model.diffusion_model.base_model.model.middle_block.1.transformer_blocks.0.attn1.to_k.lora_A.default.weight', 'model.diffusion_model.base_model.model.middle_block.1.transformer_blocks.0.attn1.to_k.lora_B.default.weight', 'model.diffusion_model.base_model.model.middle_block.1.transformer_blocks.0.attn1.to_v.lora_A.default.weight', 'model.diffusion_model.base_model.model.middle_block.1.transformer_blocks.0.attn1.to_v.lora_B.default.weight', 'model.diffusion_model.base_model.model.output_blocks.9.1.transformer_blocks.0.attn1.to_q.lora_A.default.weight', 'model.diffusion_model.base_model.model.output_blocks.9.1.transformer_blocks.0.attn1.to_q.lora_B.default.weight', 'model.diffusion_model.base_model.model.output_blocks.9.1.transformer_blocks.0.attn1.to_k.lora_A

In [2]:
for n, p in model.named_modules():
    print(n)


model
model.diffusion_model
model.diffusion_model.base_model
model.diffusion_model.base_model.model
model.diffusion_model.base_model.model.time_embed
model.diffusion_model.base_model.model.time_embed.0
model.diffusion_model.base_model.model.time_embed.1
model.diffusion_model.base_model.model.time_embed.2
model.diffusion_model.base_model.model.input_blocks
model.diffusion_model.base_model.model.input_blocks.0
model.diffusion_model.base_model.model.input_blocks.0.0
model.diffusion_model.base_model.model.input_blocks.1
model.diffusion_model.base_model.model.input_blocks.1.0
model.diffusion_model.base_model.model.input_blocks.1.0.in_layers
model.diffusion_model.base_model.model.input_blocks.1.0.in_layers.0
model.diffusion_model.base_model.model.input_blocks.1.0.in_layers.1
model.diffusion_model.base_model.model.input_blocks.1.0.in_layers.2
model.diffusion_model.base_model.model.input_blocks.1.0.h_upd
model.diffusion_model.base_model.model.input_blocks.1.0.emb_layers
model.diffusion_model.

In [4]:
print(model)

TossLoraModule(
  (model): DiffusionWrapper(
    (diffusion_model): PeftModel(
      (base_model): LoraModel(
        (model): UNetModel_toss(
          (time_embed): Sequential(
            (0): Linear(in_features=320, out_features=1280, bias=True)
            (1): SiLU()
            (2): Linear(in_features=1280, out_features=1280, bias=True)
          )
          (input_blocks): ModuleList(
            (0): TimestepEmbedSequential(
              (0): Conv2d(4, 320, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
            )
            (1-2): 2 x TimestepEmbedSequential(
              (0): ResBlock(
                (in_layers): Sequential(
                  (0): GroupNorm32(32, 320, eps=1e-05, affine=True)
                  (1): SiLU()
                  (2): Conv2d(320, 320, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
                )
                (h_upd): Identity()
                (x_upd): Identity()
                (emb_layers): Sequential(
                  (0): S

In [5]:
trainable = [n for n, p in model.named_parameters() if p.requires_grad]
print("Trainable parameters:", len(trainable))
for n in trainable:
    print(n)

Trainable parameters: 32
model.diffusion_model.base_model.model.middle_block.1.transformer_blocks.0.attn1.to_q.lora_A.default.weight
model.diffusion_model.base_model.model.middle_block.1.transformer_blocks.0.attn1.to_q.lora_B.default.weight
model.diffusion_model.base_model.model.middle_block.1.transformer_blocks.0.attn1.to_k.lora_A.default.weight
model.diffusion_model.base_model.model.middle_block.1.transformer_blocks.0.attn1.to_k.lora_B.default.weight
model.diffusion_model.base_model.model.middle_block.1.transformer_blocks.0.attn1.to_v.lora_A.default.weight
model.diffusion_model.base_model.model.middle_block.1.transformer_blocks.0.attn1.to_v.lora_B.default.weight
model.diffusion_model.base_model.model.output_blocks.9.1.transformer_blocks.0.attn1.to_q.lora_A.default.weight
model.diffusion_model.base_model.model.output_blocks.9.1.transformer_blocks.0.attn1.to_q.lora_B.default.weight
model.diffusion_model.base_model.model.output_blocks.9.1.transformer_blocks.0.attn1.to_k.lora_A.default.w

# Pose Methods

In [6]:
import numpy as np

def rotation_matrix_to_euler(R):
    """
    Extract pitch (x-rotation) and yaw (y-rotation) from a 3x3 rotation matrix.
    Returns angles in radians.
    
    Assumes rotation order: R = Ry(yaw) @ Rx(pitch) @ Rz(roll)
    """
    # Clamp to avoid numerical issues with asin
    sy = np.clip(R[0, 2], -1.0, 1.0)
    yaw = np.arcsin(sy)
    
    # Check for gimbal lock
    if np.abs(sy) < 0.99999:
        pitch = np.arctan2(-R[1, 2], R[2, 2])
    else:
        pitch = np.arctan2(R[2, 1], R[1, 1])
    
    return pitch, yaw


def pose_matrix_to_toss_format(pose_4x4):
    """
    Convert a 4x4 pose matrix to TOSS format: [pitch, yaw, distance]
    
    Args:
        pose_4x4: 4x4 transformation matrix (camera-to-world or world-to-camera)
    
    Returns:
        [pitch, yaw, distance] as expected by TOSS pose_enc="vae" or "freq"
    """
    R = pose_4x4[:3, :3]  # 3x3 rotation
    t = pose_4x4[:3, 3]   # translation vector
    
    pitch, yaw = rotation_matrix_to_euler(R)
    
    # Distance: typically the Z component or the norm of translation
    # Adjust based on your coordinate system
    distance = np.linalg.norm(t)  # or t[2] if Z is the depth axis
    
    return np.array([pitch, yaw, distance], dtype=np.float32)


def compute_relative_pose(src_pose_4x4, tgt_pose_4x4):
    """
    Compute relative pose from source to target view.
    Returns [delta_pitch, delta_yaw, delta_distance] in radians.
    """
    src_pitch, src_yaw = rotation_matrix_to_euler(src_pose_4x4[:3, :3])
    tgt_pitch, tgt_yaw = rotation_matrix_to_euler(tgt_pose_4x4[:3, :3])
    
    src_dist = np.linalg.norm(src_pose_4x4[:3, 3])
    tgt_dist = np.linalg.norm(tgt_pose_4x4[:3, 3])
    
    delta_pitch = tgt_pitch - src_pitch
    delta_yaw = tgt_yaw - src_yaw
    delta_distance = tgt_dist - src_dist
    
    return np.array([delta_pitch, delta_yaw, delta_distance], dtype=np.float32)

# Debug: Check poses.npy format and values
import numpy as np

sub_path = "datasets/portrait4d/202483"
poses = np.load(f"{sub_path}/poses.npy")

print(f"Poses shape: {poses.shape}")
print(f"Poses dtype: {poses.dtype}")

# Reshape if needed
if poses.ndim == 2 and poses.shape[1] == 16:
    poses = poses.reshape(-1, 4, 4)
    print(f"Reshaped to: {poses.shape}")

# Check a single pose matrix
print(f"\nPose[0] (view 00000):\n{poses[0]}")
print(f"\nPose[9] (view 00009 - center):\n{poses[9]}")

# Check if it looks like a valid rotation matrix
R = poses[0][:3, :3]
print(f"\nRotation matrix R (from pose[0]):\n{R}")
print(f"det(R) = {np.linalg.det(R):.6f} (should be ~1.0 for valid rotation)")
print(f"R @ R.T =\n{R @ R.T} (should be ~identity)")

# Extract angles using your function
pitch, yaw = rotation_matrix_to_euler(R)
print(f"\nExtracted angles from pose[0]:")
print(f"  pitch = {pitch:.4f} rad = {np.degrees(pitch):.2f}°")
print(f"  yaw = {yaw:.4f} rad = {np.degrees(yaw):.2f}°")

# Check all poses' yaw values
print(f"\nAll yaw values (degrees):")
for i in range(min(20, len(poses))):
    p, y = rotation_matrix_to_euler(poses[i][:3, :3])
    print(f"  View {i:02d}: pitch={np.degrees(p):+7.2f}°, yaw={np.degrees(y):+7.2f}°")

Poses shape: (20, 16)
Poses dtype: float32
Reshaped to: (20, 4, 4)

Pose[0] (view 00000):
[[ 9.5087630e-01  3.8671235e-09  3.0957130e-01  1.2411852e+00]
 [-3.9345893e-16  1.0000000e+00 -1.2491868e-08 -5.0084495e-08]
 [-3.0957130e-01  1.1878219e-08  9.5087630e-01  4.0124130e+00]
 [ 0.0000000e+00  0.0000000e+00  0.0000000e+00  1.0000000e+00]]

Pose[9] (view 00009 - center):
[[ 9.9986261e-01  2.0757676e-10  1.6578235e-02  6.6313364e-02]
 [-5.3748079e-18  1.0000000e+00 -1.2521043e-08 -5.0084495e-08]
 [-1.6578235e-02  1.2519321e-08  9.9986261e-01  4.1994762e+00]
 [ 0.0000000e+00  0.0000000e+00  0.0000000e+00  1.0000000e+00]]

Rotation matrix R (from pose[0]):
[[ 9.5087630e-01  3.8671235e-09  3.0957130e-01]
 [-3.9345893e-16  1.0000000e+00 -1.2491868e-08]
 [-3.0957130e-01  1.1878219e-08  9.5087630e-01]]
det(R) = 1.000000 (should be ~1.0 for valid rotation)
R @ R.T =
[[ 1.0000001e+00 -6.9490541e-16  1.8047803e-09]
 [-6.9490541e-16  1.0000000e+00 -1.8567293e-15]
 [ 1.8047803e-09 -1.8567293e-15 

# Portrait4D Dataset

In [ ]:
import os
from PIL import Image
from torch.utils.data import Dataset
import numpy as np
import torch
from torchvision import transforms as T

import os

def preprocess_normal_for_cosine(normal_rgb, valid_eps=0.1):
    """
    Preprocess normal map for cosine similarity loss.
    
    Args:
        normal_rgb: [H, W, 3] or [3, H, W], values in [0, 1] (standard normal map: RGB = xyz)
        valid_eps: pixels with magnitude < valid_eps in [0,1] space are invalid (e.g. black)
    
    Returns:
        normal: [3, H, W] L2-normalized, in [-1, 1] range
        valid_mask: [1, H, W] float, 1 where valid, 0 where invalid
    """
    if isinstance(normal_rgb, np.ndarray):
        normal = torch.from_numpy(normal_rgb).float()
    else:
        normal = normal_rgb.float()
    
    if normal.ndim == 3 and normal.shape[-1] == 3:
        normal = normal.permute(2, 0, 1)  # HWC -> CHW
    
    # Valid region: pixels where magnitude in [0,1] space > eps (exclude black/invalid)
    mag = normal.norm(dim=0, keepdim=True)
    valid_mask = (mag.squeeze(0) > valid_eps).float().unsqueeze(0)
    
    # RGB [0, 1] -> xyz [-1, 1]
    normal = normal * 2.0 - 1.0
    
    # L2 normalize per pixel (for cosine similarity)
    norm = normal.norm(dim=0, keepdim=True).clamp(min=1e-8)
    normal = normal / norm
    
    return normal, valid_mask
class Portrait4dDataset(Dataset):
    def __init__(self, root_dir, transform=None, src_view_idx=9, skip_identity=True, load_normals=True, load_depth=True):
        super().__init__()
        self.root_dir = root_dir
        self.transform = transform
        self.src_view_idx = src_view_idx
        self.skip_identity = skip_identity
        self.load_normals = load_normals
        self.load_depth = load_depth

        self.subjects = [d for d in os.listdir(root_dir)
                         if os.path.isdir(os.path.join(root_dir, d))]
        self.samples = []
        skipped = 0

        for sub in self.subjects:
            sub_path = os.path.join(root_dir, sub)
            poses_path = os.path.join(sub_path, 'poses.npy')
            if not os.path.exists(poses_path):
                skipped += 1
                continue

            views = sorted([f for f in os.listdir(sub_path)
                           if f.endswith('.jpg') and not f.startswith('src')])

            for view_file in views:
                view_id = view_file.split('.')[0]
                view_index = int(view_id)
                if self.skip_identity and view_index == self.src_view_idx:
                    continue

                mask_file = f"{view_id}_mask.png"
                normal_file = os.path.join("normals", f"{view_id}.png")
                normal_path = os.path.join(sub_path, normal_file)
                depth_file = os.path.join("depth", f"{view_id}.npy")
                depth_path = os.path.join(sub_path, depth_file)

                has_mask = os.path.exists(os.path.join(sub_path, mask_file))
                has_normal = os.path.exists(normal_path) if self.load_normals else True
                has_depth = os.path.exists(depth_path) if self.load_depth else True

                if has_mask and has_normal and has_depth:
                    self.samples.append({
                        'sub_path': sub_path,
                        'view_file': view_file,
                        'mask_file': mask_file,
                        'normal_file': normal_file,
                        'depth_file': depth_file,
                        'view_index': view_index,
                    })

        parts = []
        if self.load_normals:
            parts.append("normals")
        if self.load_depth:
            parts.append("depth")
        extra_str = f" (with {', '.join(parts)})" if parts else ""
        print(f"[Dataset] Loaded {len(self.samples)} samples{extra_str}, skipped {skipped} incomplete subjects")

    def __len__(self):
        return len(self.samples)

    def __getitem__(self, idx):
        sample = self.samples[idx]
        sub_path = sample['sub_path']

        src_path = os.path.join(sub_path, f"{self.src_view_idx:05d}.jpg")
        src = Image.open(src_path).convert("RGB")

        img_path = os.path.join(sub_path, sample['view_file'])
        image = Image.open(img_path).convert("RGB")

        mask_path = os.path.join(sub_path, sample['mask_file'])
        mask = Image.open(mask_path).convert("L")

        poses = np.load(os.path.join(sub_path, 'poses.npy'))
        if poses.ndim == 2 and poses.shape[1] == 16:
            poses = poses.reshape(-1, 4, 4)

        delta_pose = compute_relative_pose(
            poses[self.src_view_idx],
            poses[sample['view_index']]
        )
        assert abs(delta_pose[1]) < 1.0, f"Yaw {delta_pose[1]} seems too large - check units!"
        delta_pose = torch.from_numpy(delta_pose).float()

        if self.transform:
            src = self.transform(src)
            image = self.transform(image)

        mask_transform = T.Compose([T.Resize((256, 256)), T.ToTensor()])
        mask = mask_transform(mask)

        out = {
            "jpg": image,
            "hint": src,
            "mask": mask,
            "delta_pose": delta_pose,
            "subject_id": os.path.basename(sub_path),
            "txt": ""
        }

        if self.load_normals:
            normal_path = os.path.join(sub_path, sample['normal_file'])
            normal_img = Image.open(normal_path).convert("RGB")
            normal_img = normal_img.resize((256, 256), Image.BILINEAR)
            normal_np = np.array(normal_img).astype(np.float32) / 255.0
            normal, normal_valid_mask = preprocess_normal_for_cosine(normal_np, valid_eps=0.1)
            out["normal"] = normal
            out["normal_mask"] = normal_valid_mask

        if self.load_depth:
            depth_path = os.path.join(sub_path, sample['depth_file'])
            depth_np = np.load(depth_path).astype(np.float32)
            if depth_np.ndim == 3: # Handles arrays that are (H, W, 1) or (1, H, W) to (H, W)
                depth_np = depth_np.squeeze()
            depth_t = torch.from_numpy(depth_np).float().unsqueeze(0) # Converts to a tensor and adds a channel dimension, giving shape [1, H, W]
            depth_t = torch.nn.functional.interpolate( 
                depth_t.unsqueeze(0), size=(256, 256),
                mode='bilinear', align_corners=False
            ).squeeze(0) # Returns a tensor with shape [1, H, W]
            valid = (depth_t > 1e-6) & (depth_t < 1e6) & (~torch.isnan(depth_t)) & (~torch.isinf(depth_t)) # Filters out invalid depth values
            depth_mask = valid.float()
            out["depth"] = depth_t
            out["depth_mask"] = depth_mask

        return out


# Load Dataset

In [ ]:
from torchvision import transforms as T
from torch.utils.data import Dataset, DataLoader

transform = T.Compose([
    T.Resize((256, 256)),
    T.ToTensor(),
    # T.Normalize([0.5], [0.5])
])

dataset_name = "portrait4d_rembg"
dataset = Portrait4dDataset(
    root_dir=f"datasets/portrait4d_rembg", transform=transform
)

dataloader = DataLoader(dataset, batch_size=4, shuffle=True, num_workers=0)

data_iter = iter(dataloader)
batch = next(data_iter)
print("Batch keys:", batch.keys())

[Dataset] Loaded 1881 samples (with normals), skipped 1 incomplete subjects
Batch keys: dict_keys(['jpg', 'hint', 'mask', 'delta_pose', 'subject_id', 'txt', 'normal', 'normal_mask'])


# Training

In [ ]:
import pytorch_lightning as pl
from pytorch_lightning.callbacks import ModelCheckpoint

checkpoint_cb = ModelCheckpoint(
    dirpath="checkpoints/v2/",
    filename="toss-{step}",
    save_last=True,
    every_n_train_steps=500
)

trainer = pl.Trainer(
    max_steps=25000, # 1 step = 1 batch(4)
    accelerator="gpu",
    devices=1,
    callbacks=[checkpoint_cb],
    log_every_n_steps=10,
    gradient_clip_val=1.0,
    enable_checkpointing=True,
)

# Additional Config
model.learning_rate = 1e-5
model.sd_locked = True
model.first_stage_key = "jpg"
model.control_key = "hint"
model.cond_stage_key = "txt"

import torch.utils.checkpoint as cp
cp.checkpoint = lambda func, *args, **kwargs: func(*args)

trainer.fit(model, dataloader)

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs


NameError: name 'model' is not defined

# Inference

## Load Model + Original Checkpoint

In [2]:
from PIL import Image
import numpy as np
import torchvision.transforms as T

# Load the last checkpoint
import torch
from cldm.toss import TOSS
from cldm.toss_lora import TossLoraModule
from cldm.model import load_state_dict
from omegaconf import OmegaConf
from PIL import Image
from torchvision import transforms as T

from ldm.util import instantiate_from_config

config = OmegaConf.load("models/toss_vae.yaml")
model = instantiate_from_config(config.model)

print(isinstance(model, TossLoraModule))

state_dict = torch.load("ckpt/toss.ckpt", map_location="cpu", weights_only=False)["state_dict"]

model.load_state_dict(state_dict, strict=False)

for n, p in model.named_parameters():
   if "lora" in n.lower() or ".out." in n.lower():
       print(n, p.abs().mean().item())

TOSS: Running in eps-prediction mode
DiffusionWrapper has 863.65 M params.
making attention of type 'vanilla' with 512 in_channels
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla' with 512 in_channels
False
model.diffusion_model.out.0.weight 0.40596455335617065
model.diffusion_model.out.0.bias 0.3524356484413147
model.diffusion_model.out.2.weight 0.02248171716928482
model.diffusion_model.out.2.bias 0.002517908113077283


## Load Trained Checkpoint

In [ ]:
trained_ckpt = torch.load("checkpoints/v2/last-v12.ckpt", map_location="cpu", weights_only=False)

lora_keys = [k for k in trained_ckpt["state_dict"].keys() if "lora" in k.lower()]
print(f"Found {len(lora_keys)} LoRA keys in checkpoint:")
for k in lora_keys:
    print(f"  {k}: {trained_ckpt['state_dict'][k].abs().mean().item():.6f}")

# This will inject your LoRA weights and your trained PoseNet
m, u = model.load_state_dict(trained_ckpt["state_dict"], strict=False)

print()

for n, p in model.named_parameters():
   if "lora" in n.lower() or ".out." in n.lower():
       print(n, p.abs().mean().item())

print("Missing:", m)
print("Unexpected keys (should be empty):", u)

In [3]:
trainable = [n for n, p in model.named_parameters() if p.requires_grad]
print("Trainable parameters:", len(trainable))
for n in trainable:
    print(n)

Trainable parameters: 722
model.diffusion_model.time_embed.0.weight
model.diffusion_model.time_embed.0.bias
model.diffusion_model.time_embed.2.weight
model.diffusion_model.time_embed.2.bias
model.diffusion_model.input_blocks.0.0.weight
model.diffusion_model.input_blocks.0.0.bias
model.diffusion_model.input_blocks.1.0.in_layers.0.weight
model.diffusion_model.input_blocks.1.0.in_layers.0.bias
model.diffusion_model.input_blocks.1.0.in_layers.2.weight
model.diffusion_model.input_blocks.1.0.in_layers.2.bias
model.diffusion_model.input_blocks.1.0.emb_layers.1.weight
model.diffusion_model.input_blocks.1.0.emb_layers.1.bias
model.diffusion_model.input_blocks.1.0.out_layers.0.weight
model.diffusion_model.input_blocks.1.0.out_layers.0.bias
model.diffusion_model.input_blocks.1.0.out_layers.3.weight
model.diffusion_model.input_blocks.1.0.out_layers.3.bias
model.diffusion_model.input_blocks.1.1.norm.weight
model.diffusion_model.input_blocks.1.1.norm.bias
model.diffusion_model.input_blocks.1.1.proj_

## Inference v1 (Manually typed inference)

In [ ]:
model.cuda()
model.eval()

# source image
img_name = "00010.jpg"
src_img = Image.open(f"examples/{img_name}").convert("RGB")

transform = T.Compose([
    T.Resize((256, 256)),
    T.ToTensor(),
    T.Normalize([0.5]*3, [0.5]*3)  # → [-1,1]
])

src_img = transform(src_img)
src_img = src_img.unsqueeze(0).cuda()
print(src_img.shape)

with torch.no_grad():
    z = model.encode_first_stage(src_img)
    z = model.get_first_stage_encoding(z)
print(z.shape)

# with torch.no_grad():
#     hint_post = model.encode_first_stage(src_img)
#     hint_latent = hint_post.mode() if hasattr(hint_post, "mode") else hint_post



# pose (example)
# delta_pose = torch.eye(4)[:3]   # (3,4)
# delta_pose = delta_pose.unsqueeze(0).cuda()
# delta_pose = torch.tensor([[0.0, 0.0, 0.0]], device="cuda")  # [B=1, 3]
# delta_pose = create_rotation_matrix(yaw_deg=30).cuda()

print("pose_net in_features:", model.model.diffusion_model.pose_net[0].in_features)

yaw_deg = 0
yaw = yaw_deg * torch.pi / 180
delta_pose = torch.tensor([[yaw, 45.0, 180.0]])
# delta_pose = torch.zeros(1, 16).cuda()
# delta_pose = torch.randn(1, 16).cuda() * 0.5
# delta_pose = torch.tensor([[9.50876296e-01, 3.86712351e-09,  3.09571296e-01,  1.24118519e+00,
#   -3.93458927e-16,  1.00000000e+00, -1.24918680e-08, -5.00844948e-08,
#   -3.09571296e-01,  1.18782193e-08,  9.50876296e-01,  4.01241302e+00,
#    0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000000e+00]], device="cuda")
print("DELTA_POSE:", delta_pose.shape)

# delta_pose_cfg = delta_pose.repeat(2, 1) # Shape becomes [2, 16]


# empty text
txt = [""]

batch = {
        "jpg": src_img,
        "hint": src_img,
        # 'mask': mask,
        "delta_pose": delta_pose, # pose from original angle
        # "subject_id": os.path.basename(sub_path),
        "txt": txt
    }

print(src_img.shape)
print(delta_pose.shape)

x_T = torch.randn_like(z)

# cond = {
#     "in_concat": [z],
#     "c_crossattn": [model.get_learned_conditioning(txt)],
#     "c_concat": [src_img],
#     "delta_pose": delta_pose,
# }

# uc_cond = {
#     "in_concat": [z * 0],
#     "c_crossattn": [model.get_unconditional_conditioning(1)],
#     "c_concat": [src_img],
#     "delta_pose": delta_pose,
# }

x, cond = model.get_input(batch, model.first_stage_key)
# cond["delta_pose"] = torch.zeros_like(cond["delta_pose"])
print("COND", cond)

from ldm.models.diffusion.ddim import DDIMSampler
from torchvision.utils import save_image

sampler = DDIMSampler(model)

# with torch.no_grad():
#     samples, _ = sampler.sample(
#         S=50,                      # inference steps
#         batch_size=1,
#         shape=(4, 64, 64),         # latent shape (예시)
#         conditioning=cond,         # conditioning (same as training)
#         unconditional_guidance_scale=7.5,
#         unconditional_conditioning=uc_cond,
#         eta=0.0
#     )

# txt2img
# with torch.no_grad():
#     samples, _ = sampler.sample(
#         S=20,                      # inference steps
#         batch_size=1,
#         shape=(z.shape[1], z.shape[2], z.shape[3]),         # latent shape
#         conditioning=cond,         # conditioning (same as training)
#         unconditional_guidance_scale=1,
#         # unconditional_conditioning=uc_cond,
#         # eta=0.0
#     )

print("loaded?", any((p.abs().mean().item() > 0) for p in model.parameters()))
print("z:", z.shape, z.abs().mean().item(), z.std().item())
print("cond keys:", cond.keys(), {k: type(v) for k,v in cond.items()})

# img2img
sampler.make_schedule(
    ddim_num_steps=50,
    ddim_eta=0.0,
    verbose=False
)

print(sampler.ddim_timesteps)

strength = 0.4
t_enc = int(strength * len(sampler.ddim_timesteps))
z_enc = sampler.stochastic_encode(z, torch.tensor([t_enc]).cuda())

print("x_dec batch:", z_enc.shape[0])
print("cond delta_pose batch:", cond["delta_pose"].shape[0])
print("cond crossattn batch:", cond["c_crossattn"][0].shape[0])
print("cond in_concat batch:", cond["in_concat"][0].shape[0])


# Decode
samples = sampler.decode(
    z_enc,
    cond,
    t_enc,
    unconditional_guidance_scale=3.0,
    unconditional_conditioning=None
)

# Decode
with torch.no_grad():
    out = model.decode_first_stage(samples)
out = torch.clamp((out + 1) / 2, 0, 1)
print(out.shape)
save_image(out, "test_output.png")


# LOSS
    # Perceptual Loss, Contrastive Loss






torch.Size([1, 3, 256, 256])
torch.Size([1, 4, 32, 32])
pose_net in_features: 51
DELTA_POSE: torch.Size([1, 3])
torch.Size([1, 3, 256, 256])
torch.Size([1, 3])
get_input raw control: torch.Size([1, 3, 256, 256])
COND {'c_crossattn': [tensor([[[-0.3884,  0.0229, -0.0522,  ..., -0.4899, -0.3066,  0.0675],
         [-0.3711, -1.4497, -0.3401,  ...,  0.9489,  0.1867, -1.1034],
         [-0.5107, -1.4629, -0.2926,  ...,  1.0419,  0.0701, -1.0284],
         ...,
         [ 0.5006, -0.9552, -0.6610,  ...,  1.6013, -1.0622, -0.2191],
         [ 0.4988, -0.9451, -0.6656,  ...,  1.6467, -1.0858, -0.2088],
         [ 0.4924, -0.8124, -0.4912,  ...,  1.6108, -1.0174, -0.2484]]],
       device='cuda:0')], 'c_concat': [tensor([[[[ 0.6863,  0.7176,  0.7098,  ...,  0.7098,  0.7098,  0.6863],
          [ 0.7098,  0.7176,  0.7098,  ...,  0.7098,  0.7098,  0.7098],
          [ 0.7098,  0.7176,  0.7098,  ...,  0.7098,  0.7098,  0.7176],
          ...,
          [ 0.7255,  0.7255,  0.7098,  ...,  0.3490,  

Decoding image: 100%|██████████| 20/20 [00:00<00:00, 34.79it/s]

torch.Size([1, 3, 256, 256])


## Inference v2 (Inference code used in Gradio)

In [4]:
# TOSS app.py to ipynb
model.cuda()
model.eval()

# source image
img_name = "man_out.png"
src_img = Image.open(f"examples/{img_name}").convert("RGB")

transform = T.Compose([
    T.Resize((256, 256)),
    T.ToTensor(),
    # T.Normalize([0.5]*3, [0.5]*3)  # → [-1,1]
])

src_img = transform(src_img)
src_img = src_img.unsqueeze(0).cuda()
print(src_img.shape)

with torch.no_grad():
    z = model.encode_first_stage(src_img)
    z = model.get_first_stage_encoding(z)
print(z.shape)

print("pose_net in_features:", model.model.diffusion_model.pose_net[0].in_features)

# empty text
txt = [""]

# batch = {
#         "jpg": src_img,
#         "hint": src_img,
#         # 'mask': mask,
#         "delta_pose": delta_pose, # pose from original angle
#         # "subject_id": os.path.basename(sub_path),
#         "txt": txt
#     }

n_samples = 1
prompt_scale = 0.0
img_scale = 1.0
ddim_steps = 50
ddim_eta = 0.0
h = 256
w = 256

import math
def get_T_from_relative(x, y, z, pose_enc="freq")->torch.Tensor:
    """
    Args:
        x: relative polar degree
        y: relative azimuth degree
        z: relative distance
        
    example:
        (0., -90., 0.): left view
        (0., 90., 0.): right view
        (0., 180., 0.): back view
        (-90., 0., 0.): top view
        (90., 0., 0.): bottom view
    """
    print("POSE_ENC:", pose_enc)
    if pose_enc in ["freq","identity", "vae"]:
        d_T = torch.tensor([math.radians(x), math.radians(y), z])
    elif pose_enc == "zero":
        d_T = torch.tensor([math.radians(x), math.sin(
                math.radians(y)), math.cos(math.radians(y)), z])
    else:
        raise NotImplementedError
    return d_T

# Pose
yaw_deg = -30.0
yaw_rad = math.radians(yaw_deg)
delta_pose = torch.tensor([[0.0, yaw_rad, 0.0]], device='cuda')


# hint
c_cat = src_img

# text
uc_cross = model.get_unconditional_conditioning(n_samples)
c = model.get_learned_conditioning(txt)
# camera pose
# delta_pose = T[None, :].repeat(n_samples, 1).to(c.device)
# concat for concat pipline
in_concat = model.encode_first_stage(((src_img*2-1).to(c.device))).mode().detach()


cond = {}
cond['delta_pose'] = delta_pose
cond['c_crossattn'] = [c]
cond['c_concat'] = [c_cat]
cond['in_concat'] = [in_concat]

# uc2 for prompt
uc2 = {}
uc2['delta_pose'] = delta_pose
uc2['c_crossattn'] = [uc_cross]
uc2['c_concat'] = [c_cat]
uc2['in_concat'] = [in_concat]
            
# uc for image
uc = {}
uc['delta_pose'] = delta_pose
uc['c_crossattn'] = [uc_cross]
uc['c_concat'] = [c_cat]
uc['in_concat'] = [in_concat*0] 

from ldm.models.diffusion.ddim import DDIMSampler
from torchvision.utils import save_image

sampler = DDIMSampler(model)

shape = [4, h // 8, w // 8]
x_T = torch.randn(in_concat.shape, device=c.device)
samples_ddim, _ = sampler.sample(S=ddim_steps,
                                conditioning=cond,
                                batch_size=n_samples,
                                shape=shape,
                                verbose=False,
                                unconditional_guidance_scale=img_scale,
                                unconditional_conditioning=uc,
                                unconditional_guidance_scale2=prompt_scale,
                                unconditional_conditioning2=uc2,
                                eta=ddim_eta,
                                x_T=x_T)


print(samples_ddim.shape)
x_samples_ddim = model.decode_first_stage(samples_ddim)

out = torch.clamp((x_samples_ddim + 1.0) / 2.0, min=0.0, max=1.0).cpu()

print(out.shape)
save_image(out, "test_output.png")

torch.Size([1, 3, 256, 256])
torch.Size([1, 4, 32, 32])
pose_net in_features: 51


c:\Users\user\.conda\envs\toss\lib\site-packages\transformers\integrations\sdpa_attention.py:96: UserWarning: 1Torch was not compiled with flash attention. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\transformers\cuda\sdp_utils.cpp:555.)
  attn_output = torch.nn.functional.scaled_dot_product_attention(


Data shape for DDIM sampling is (1, 4, 32, 32), eta 0.0
Running DDIM Sampling with 50 timesteps


DDIM Sampler: 100%|██████████| 50/50 [00:01<00:00, 33.23it/s]


torch.Size([1, 4, 32, 32])
torch.Size([1, 3, 256, 256])
